#ifndef _BASE_CONTROLLER_CONSTS_h
#define _BASE_CONTROLLER_CONSTS_h


#include "Base_Consts.h"

static int const BASE_CONTROLLER_FIRST_MESSAGE = BASE_FIRST_MESSAGE + 200000;
static int const BASE_CONTROLLER_LAST_MESSAGE = BASE_CONTROLLER_FIRST_MESSAGE;

#endif