#ifndef _BUTTON_DEVICE_DRIVER_CONSTS_h
#define _BUTTON_DEVICE_DRIVER_CONSTS_h

#include "Device_Driver_Consts.h"

static unsigned int const BUTTON_DEVICE_DRIVER_TYPE = DEVICE_DRIVER_LAST_MESSAGE + 1002000;
static unsigned int const BUTTON_DEVICE_DRIVER_PUSH_BUTTON = BUTTON_DEVICE_DRIVER_TYPE + 1;

static unsigned int const BUTTON_DEVICE_BUTTONSTATE_TRACKING = BUTTON_DEVICE_DRIVER_TYPE + 50;
static unsigned int const BUTTON_DEVICE_BUTTONSTATE_PRESSED = BUTTON_DEVICE_DRIVER_TYPE + 51;
static unsigned int const BUTTON_DEVICE_BUTTONSTATE_AUTOREPEAT = BUTTON_DEVICE_DRIVER_TYPE + 52;
static unsigned int const BUTTON_DEVICE_BUTTONSTATE_RELEASED = BUTTON_DEVICE_DRIVER_TYPE + 53;

static unsigned int const BUTTON_DEVICE_DRIVER_LAST_MESSAGE = BUTTON_DEVICE_BUTTONSTATE_RELEASED;

#endif

