#ifndef _BUTTON_DEVICE_DRIVER_CONSTS_h
#define _BUTTON_DEVICE_DRIVER_CONSTS_h

#include "Device_Driver_Consts.h"

static unsigned int const BUTTON_DEVICE_DRIVER_FIRST_MESSAGE = DEVICE_DRIVER_LAST_MESSAGE + 1001000;
static unsigned int const BUTTON_DEVICE_DRIVER_PUSH_BUTTON = BUTTON_DEVICE_DRIVER_FIRST_MESSAGE + 1;
static unsigned int const BUTTON_DEVICE_DRIVER_LAST_MESSAGE = LED_DEVICE_DRIVER_PIN_PULSE;

#endif