#ifndef _BUTTON_DEVICE_DRIVER_CONSTS_h
#define _BUTTON_DEVICE_DRIVER_CONSTS_h

#include "Device_Driver_Consts.h"

static unsigned int const BUTTON_DEVICE_DRIVER_TYPE = DEVICE_DRIVER_LAST_MESSAGE + 1002000;
static unsigned int const BUTTON_DEVICE_DRIVER_PUSH_BUTTON = BUTTON_DEVICE_DRIVER_TYPE + 1;
static unsigned int const BUTTON_DEVICE_DRIVER_LAST_MESSAGE = BUTTON_DEVICE_DRIVER_PUSH_BUTTON;

#endif

