#ifndef DISTANCE_DEVICE_DRIVER_CONSTS_h
#define DISTANCE_DEVICE_DRIVER_CONSTS_h

#include "Device_Driver_Consts.h"

static unsigned int const DISTANCE_DEVICE_DRIVER_FIRST_MESSAGE = DEVICE_DRIVER_LAST_MESSAGE + 1002000;
static unsigned int const DISTANCE_DEVICE_DRIVER_LAST_MESSAGE = DISTANCE_DEVICE_DRIVER_FIRST_MESSAGE;

#endif