#ifndef _LED_BUTTON_MODULE_DRIVER_CONSTS_h
#define _LED_BUTTON_MODULE_DRIVER_CONSTS_h

#include "Module_Driver_Consts.h"

static unsigned int const LED_BUTTON_MODULE_DRIVER_FIRST_MESSAGE = MODULE_DRIVER_LAST_MESSAGE + 1000000;
static unsigned int const LED_BUTTON_MODULE_DRIVER_LAST_MESSAGE = LED_BUTTON_MODULE_DRIVER_FIRST_MESSAGE;

#endif