#ifndef LUXMETER_DEVICE_DRIVER_CONSTS_h
#define LUXMETER_DEVICE_DRIVER_CONSTS_h

#include "Device_Driver_Consts.h"

static unsigned int const LUXMETER_DEVICE_DRIVER_FIRST_MESSAGE = DEVICE_DRIVER_LAST_MESSAGE + 1004000;
static unsigned int const LUXMETER_DEVICE_DRIVER_SET_ACCURACY = LUXMETER_DEVICE_DRIVER_FIRST_MESSAGE + 1;
static unsigned int const LUXMETER_DEVICE_DRIVER_LAST_MESSAGE = LUXMETER_DEVICE_DRIVER_SET_ACCURACY;

#endif