#ifndef LUXMETER_DEVICE_DRIVER_CONSTS_h
#define LUXMETER_DEVICE_DRIVER_CONSTS_h

#include "Device_Driver_Consts.h"

static unsigned int const LUXMETER_DEVICE_DRIVER_TYPE = DEVICE_DRIVER_LAST_MESSAGE + 1004000;
static unsigned int const LUXMETER_DEVICE_DRIVER_SET_ACCURACY_DELAY = LUXMETER_DEVICE_DRIVER_TYPE + 1;
static unsigned int const LUXMETER_DEVICE_DRIVER_SET_INTEGRATION_TIME = LUXMETER_DEVICE_DRIVER_TYPE + 2;
static unsigned int const LUXMETER_DEVICE_DRIVER_SET_GAIN = LUXMETER_DEVICE_DRIVER_TYPE + 3;
static unsigned int const LUXMETER_DEVICE_DRIVER_ENABLE_AUTORANGE = LUXMETER_DEVICE_DRIVER_TYPE + 4;
static unsigned int const LUXMETER_DEVICE_DRIVER_LUX_VALUE = LUXMETER_DEVICE_DRIVER_TYPE + 5;
static unsigned int const LUXMETER_DEVICE_DRIVER_LAST_MESSAGE = LUXMETER_DEVICE_DRIVER_LUX_VALUE;
#endif

