#ifndef _MQQT_WIFI_MODULE_DRIVER_CONSTS_h
#define _MQQT_WIFI_MODULE_DRIVER_CONSTS_h

#include "WiFi_Module_Driver_Consts.h"

static unsigned int const MQQT_WIFI_MODULE_DRIVER_FIRST_MESSAGE = WIFI_MODULE_DRIVER_LAST_MESSAGE + 100000;
static unsigned int const MQQT_WIFI_MODULE_DRIVER_LAST_MESSAGE = MQQT_WIFI_MODULE_DRIVER_FIRST_MESSAGE;

#endif