#ifndef _NTP_WIFI_DEVICE_DRIVER_CONSTS_h
#define _NTP_WIFI_DEVICE_DRIVER_CONSTS_h

#include "Wifi_Device_Driver_Consts.h"

static unsigned int const NTP_WIFI_DEVICE_DRIVER_TYPE = DEVICE_DRIVER_LAST_MESSAGE + 1007000;
static unsigned int const NTP_WIFI_DEVICE_DRIVER_LOCAL_TIME = NTP_WIFI_DEVICE_DRIVER_TYPE + 1;
static unsigned int const NTP_WIFI_DEVICE_DRIVER_UTC_TIME = NTP_WIFI_DEVICE_DRIVER_TYPE + 2;
static unsigned int const NTP_WIFI_DEVICE_DRIVER_TIMEZONE = NTP_WIFI_DEVICE_DRIVER_TYPE + 3;
static unsigned int const NTP_WIFI_DEVICE_DRIVER_GET_TIME = NTP_WIFI_DEVICE_DRIVER_TYPE + 4;
static unsigned int const NTP_WIFI_DEVICE_DRIVER_LAST_MESSAGE = NTP_WIFI_DEVICE_DRIVER_GET_TIME;

#endif


