#ifndef _OLED_DISPLAY_DEVICE_DRIVER_CONSTS_h
#define _OLED_DISPLAY_DEVICE_DRIVER_CONSTS_h


#include "Display_Device_Driver_Consts.h"

static unsigned int const OLED_DISPLAY_DEVICE_DRIVER_TYPE = DISPLAY_DRIVER_LAST_MESSAGE + 100000;
static unsigned int const OLED_DISPLAY_DRIVER_INVERT = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 1;

//Painting
static unsigned int const OLED_DISPLAY_DRIVER_DRAW_PIXEL = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 2;
static unsigned int const OLED_DISPLAY_DRIVER_DRAW_CIRCLE = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 3;
static unsigned int const OLED_DISPLAY_DRIVER_DRAW_FILLED_CIRCLE = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 4;
static unsigned int const OLED_DISPLAY_DRIVER_DRAW_TRIANGLE = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 5;
static unsigned int const OLED_DISPLAY_DRIVER_DRAW_FILLED_TRIANGLE = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 6;
static unsigned int const OLED_DISPLAY_DRIVER_DRAW_ROUND_RECT = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 7;
static unsigned int const OLED_DISPLAY_DRIVER_DRAW_FILLED_ROUND_RECT = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 8;
static unsigned int const OLED_DISPLAY_DRIVER_DRAW_BITMAP = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 9;
static unsigned int const DISPLAY_DRIVER_DRAW_CHAR_COMPLETE = DISPLAY_DEVICE_DRIVER_TYPE + 10;

//Text
static unsigned int const OLED_DISPLAY_DRIVER_SET_TEXT_COLOR = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 11;
static unsigned int const OLED_DISPLAY_DRIVER_SET_TEXT_SIZE = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 12;
static unsigned int const OLED_DISPLAY_DRIVER_SET_TEXT_WRAP = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 13;
static unsigned int const OLED_DISPLAY_DRIVER_SET_ROTATION = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 14;
static unsigned int const OLED_DISPLAY_DRIVER_SET_FONT = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 15;

//Srcolling
static unsigned int const OLED_DISPLAY_DRIVER_START_SCROLL_DIAG_RIGHT = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 16;
static unsigned int const OLED_DISPLAY_DRIVER_START_SCROLL_DIAG_LEFT = OLED_DISPLAY_DEVICE_DRIVER_TYPE + 17;


static unsigned int const OLED_DISPLAY_DRIVER_LAST_MESSAGE = OLED_DISPLAY_DRIVER_START_SCROLL_DIAG_LEFT;


#endif

