#ifndef _PCF8574_CONTROLLER_CONSTS_h
#define _PCF8574_CONTROLLER_CONSTS_h


#include "I2C_Controller_Consts.h"

static int const PCF8574_CONTROLLER_FIRST_MESSAGE = I2C_CONTROLLER_LAST_MESSAGE + 1000;
static int const PCF8574_CONTROLLER_LAST_MESSAGE = PCF8574_CONTROLLER_FIRST_MESSAGE;

static int const PCF8574_CONTROLLER_PIN_ID_START = PCF8574_CONTROLLER_FIRST_MESSAGE + 100;


#endif