#ifndef _PICTURE_MODULE_DRIVER_CONSTS_h
#define _PICTURE_MODULE_DRIVER_CONSTS_h

#include "Module_Driver_Consts.h"

static unsigned int const PICTURE_MODULE_DRIVER_TYPE = MODULE_DRIVER_LAST_MESSAGE + 1001000;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_NEXT = PICTURE_MODULE_DRIVER_TYPE + 1;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_PREV = PICTURE_MODULE_DRIVER_TYPE + 2;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_OFF = PICTURE_MODULE_DRIVER_TYPE + 3;

static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_SWITCH_EXTERN = PICTURE_MODULE_DRIVER_TYPE + 50;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_AUTO_BRIGHTNESS_EXTERN = PICTURE_MODULE_DRIVER_TYPE + 51;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_BRIGHTNESS_EXTERN = PICTURE_MODULE_DRIVER_TYPE + 52;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_COLOR_EXTERN = PICTURE_MODULE_DRIVER_TYPE + 53;

static unsigned int const PICTURE_MODULE_DRIVER_LAST_MESSAGE = PICTURE_MODULE_DRIVER_PATTERN_COLOR_EXTERN;

#endif

