#ifndef _PICTURE_MODULE_DRIVER_CONSTS_h
#define _PICTURE_MODULE_DRIVER_CONSTS_h

#include "Module_Driver_Consts.h"

static unsigned int const PICTURE_MODULE_DRIVER_TYPE = MODULE_DRIVER_LAST_MESSAGE + 1001000;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_STANDARD_NEXT = PICTURE_MODULE_DRIVER_TYPE + 1;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_STANDARD_PREV = PICTURE_MODULE_DRIVER_TYPE + 2;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_OFF = PICTURE_MODULE_DRIVER_TYPE + 3;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_SWITCH = PICTURE_MODULE_DRIVER_TYPE + 4;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_AUTO_BRIGHTNESS = PICTURE_MODULE_DRIVER_TYPE + 5;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_REL_BRIGHTNESS = PICTURE_MODULE_DRIVER_TYPE + 6;
static unsigned int const PICTURE_MODULE_DRIVER_PATTERN_COLOR = PICTURE_MODULE_DRIVER_TYPE + 7;

static unsigned int const PICTURE_MODULE_DRIVER_LAST_MESSAGE = PICTURE_MODULE_DRIVER_PATTERN_COLOR;

#endif


