#ifndef _WEBSOCKET_WIFI_DEVICE_DRIVER_CONSTS_h
#define _WEBSOCKET_WIFI_DEVICE_DRIVER_CONSTS_h

#include "Wifi_Device_Driver_Consts.h"

static unsigned int const WEBSOCKET_WIFI_DEVICE_DRIVER_FIRST_MESSAGE = WIFI_DEVICE_DRIVER_FIRST_MESSAGE + 200;
static unsigned int const WEBSOCKET_WIFI_DEVICE_DRIVER_LAST_MESSAGE = WEBSOCKET_WIFI_DEVICE_DRIVER_FIRST_MESSAGE;

#endif

