#ifndef _WEBSOCKET_WIFI_DEVICE_DRIVER_CONSTS_h
#define _WEBSOCKET_WIFI_DEVICE_DRIVER_CONSTS_h

#include "Wifi_Device_Driver_Consts.h"

static unsigned int const WEBSOCKET_WIFI_DEVICE_DRIVER_FIRST_MESSAGE = WIFI_DEVICE_DRIVER_FIRST_MESSAGE + 200;
static unsigned int const WEBSOCKET_WIFI_DEVICE_DRIVER_LAST_MESSAGE = WEBSOCKET_WIFI_DEVICE_DRIVER_FIRST_MESSAGE;

static void SendHeader(WiFiClient *_client) {
	_client->println("<!DOCTYPE html>");
	_client->println("<html>");
	_client->println("<head>");
	_client->println("    <title>Bilderrahme</title>");
	_client->println("    <meta charset=\"utf-8\">");
	_client->println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
	_client->println("    <!-- SCRIPT -->");
	_client->println("    <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js\"></script>");
	_client->println("    <script type=\"text/javascript\" src=\"dist/js/kube.min.js\"></script>");
	_client->println("    <script type=\"text/javascript\" src=\"dist/js/jscolor.min.js\"></script>");
	_client->println("    <script type=\"text/javascript\" src=\"https://rawgit.com/gionkunz/chartist-js/master/dist/chartist.js\"></script>");
	_client->println("    <!--  CSS -->");
	_client->println("    <link rel=\"stylesheet\" href=\"https://rawgit.com/gionkunz/chartist-js/master/dist/chartist.min.css\">");
	_client->println("    <link rel=\"stylesheet\" href=\"dist/css/kube.min.css\">");
	_client->println("    <script>");
	_client->println("        function update() {");
	_client->println("            var data = {");
	_client->println("                labels: [\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\"],");
	_client->println("                series: [");
	_client->println("                    [5, 2, 4, 2, 0]");
	_client->println("                ]");
	_client->println("            };");
	_client->println("            new Chartist.Line(\".chart1\", data);");
	_client->println("            new Chartist.Bar(\".chart2\", data);");
	_client->println("            new Chartist.Line(\".chart3\", data);");
	_client->println("        }");
	_client->println("		var connection=new WebSocket(\"ws://\" + location.hostname + \":81/\", [\"arduino\"]); ");
	_client->println("		connection.onopen=function (){connection.send(\"Connect \" + new Date());}; ");
	_client->println("		connection.onerror=function (error){console.log(\"WebSocket Error \", error);}; ");
	_client->println("		connection.onmessage=function (e){");
	_client->println("			if (e.data.indexOf(\"subProtocol\")==-1){ ");
	_client->println("				var jsonObject = eval(\"(\" + e.data + \")\");");
	_client->println("				var deviceId =  jsonObject._deviceId;");
	_client->println("				var cmdId =  jsonObject._cmdId;");
	_client->println("				var value =  jsonObject._value;");
	_client->println("				var unit =  jsonObject._unit;");
	_client->println("				var search_id = deviceId.toString() + \"_\" + cmdId.toString();");
	_client->println("				document.getElementById(search_id).placeholder = value + \" \" + unit;};};");
	_client->println("		function SendMessage(_deviceId, _cmdId) {");
	_client->println("			var search_id = _deviceId.toString() + \"_\" + _cmdId.toString();");
	_client->println("			var obj = new Object();");
	_client->println("			obj.deviceId = _deviceId;");
	_client->println("			obj.cmdId  = _cmdId;");
	_client->println("			obj.value = document.getElementById(search_id).value;");
	_client->println("			var jsonString= JSON.stringify(obj);");
	_client->println("			connection.send(jsonString);");
	_client->println("	};");
	_client->println("    </script>");
	_client->println("    <style>");
	_client->println("        body {");
	_client->println("            font-family: Tahoma, Verdana, Segoe, sans-serif;");
	_client->println("            margin-left: 10%;");
	_client->println("            margin-right: 10%;");
	_client->println("            background-color: #DFFFDF;");
	_client->println("            min-width: 300px;");
	_client->println("        }");
	_client->println("        .content {");
	_client->println("            padding-left: 10px;");
	_client->println("            padding-right: 10px;");
	_client->println("        }");
	_client->println("        .simple-text {");
	_client->println("            color: #e3e3e3;");
	_client->println("            text-shadow: 1px 1px 0px black;");
	_client->println("        }");
	_client->println("        a {");
	_client->println("            text-align: center;");
	_client->println("            text-decoration: none;");
	_client->println("            display: inline-block;");
	_client->println("        }");
	_client->println("            a.hover {");
	_client->println("                text-decoration: none;");
	_client->println("            }");
	_client->println("        .tabs {");
	_client->println("            background: #e3e3e3;");
	_client->println("            background: -moz-linear-gradient(top, #e3e3e3, #c8c8c8);");
	_client->println("            background: -webkit-gradient(linear, left top, left bottom, from(#e3e3e3), to(#c8c8c8));");
	_client->println("        }");
	_client->println("            .tabs a {");
	_client->println("                width: 100%;");
	_client->println("                background: transparent;");
	_client->println("                padding: 10px 25px;");
	_client->println("                position: center;");
	_client->println("            }");
	_client->println("                .tabs a:hover {");
	_client->println("                    background: white;");
	_client->println("                    text-decoration: none;");
	_client->println("                }");
	_client->println("                .tabs a:visited {");
	_client->println("                    background: white;");
	_client->println("                }");
	_client->println("            .tabs h3 {");
	_client->println("                font-family: \"Century Gothic\", CenturyGothic, Geneva, AppleGothic, sans-serif;");
	_client->println("                font-size: 1.3em;");
	_client->println("                line-height: 1.5em;");
	_client->println("                margin: 0.3em 0.7em 0.3em 0.7em;");
	_client->println("                letter-spacing: -0.1em;");
	_client->println("                color: #454545;");
	_client->println("                text-align: center;");
	_client->println("            }");
	_client->println("            .tabs li {");
	_client->println("                font-size: 1.2em;");
	_client->println("            }");
	_client->println("        .container {");
	_client->println("            background: #666;");
	_client->println("            margin: auto;");
	_client->println("            padding-top: 30px;");
	_client->println("            font-family: helvetica, arial, sans-serif;");
	_client->println("        }");
	_client->println("        .head-line {");
	_client->println("            background: #e3e3e3;");
	_client->println("            position: relative;");
	_client->println("            background: -moz-linear-gradient(top, #e3e3e3, #c8c8c8);");
	_client->println("            background: -webkit-gradient(linear, left top, left bottom, from(#e3e3e3), to(#c8c8c8));");
	_client->println("            padding: 10px 20px;");
	_client->println("            margin-left: -20px;");
	_client->println("            margin-top: 0;");
	_client->println("            width: 70%;");
	_client->println("            max-width: 550px;");
	_client->println("            min-width: 300px;");
	_client->println("            font-family: Georgia, \"Times New Roman\", serif;");
	_client->println("            -moz-box-shadow: 1px 1px 3px #292929;");
	_client->println("            -webkit-box-shadow: 1px 1px 3px #292929;");
	_client->println("            color: #454545;");
	_client->println("            text-shadow: 0 1px 0 white;");
	_client->println("        }");
	_client->println("            .head-line.small {");
	_client->println("                width: 30%;");
	_client->println("                min-width: 200px;");
	_client->println("                max-width: 250px;");
	_client->println("                font-size: 1.3em;");
	_client->println("                line-height: 0.8em;");
	_client->println("                font-family: Tahoma, Verdana, Segoe, sans-serif;");
	_client->println("            }");
	_client->println("        .arrow {");
	_client->println("            position: absolute;");
	_client->println("            width: 0;");
	_client->println("            height: 0;");
	_client->println("            line-height: 0;");
	_client->println("            border-left: 20px solid transparent;");
	_client->println("            border-top: 10px solid #c8c8c8;");
	_client->println("            top: 104%;");
	_client->println("            left: 0;");
	_client->println("        }");
	_client->println("        .button {");
	_client->println("            font-size: 18px;");
	_client->println("            font-weight: bold;");
	_client->println("            text-decoration: none;");
	_client->println("            background: #e3e3e3;");
	_client->println("            position: relative;");
	_client->println("            background: -moz-linear-gradient(top, #e3e3e3, #c8c8c8);");
	_client->println("            background: -webkit-gradient(linear, left top, left bottom, from(#e3e3e3), to(#c8c8c8));");
	_client->println("            font-family: Georgia, \"Times New Roman\", serif;");
	_client->println("            -moz-box-shadow: 1px 1px 3px #292929;");
	_client->println("            -webkit-box-shadow: 1px 1px 3px #292929;");
	_client->println("            color: #454545;");
	_client->println("            text-shadow: 0 1px 0 white;");
	_client->println("            align: left;");
	_client->println("        }");
	_client->println("            .button:hover {");
	_client->println("                background-color: #454545;");
	_client->println("                color: #454545;");
	_client->println("                box-shadow: 0 1px 5px #313131, 0 3px 3px #393939, 0 3px 10px rgba(0, 0, 0, 0.1), 0 2px 15px rgba(200, 200, 200, 0.4) inset, 0 -2px 9px rgba(0, 0, 0, 0.2) inset;");
	_client->println("            }");
	_client->println("            .button:active {");
	_client->println("                box-shadow: 0 2px 0 #393939, 0 4px 4px rgba(0, 0, 0, 0.4), 0 2px 5px rgba(0, 0, 0, 0.2) inset;");
	_client->println("                top: 2px;");
	_client->println("            }");
	_client->println("        .desc {");
	_client->println("            color: #454545;");
	_client->println("        }");
	_client->println("    </style>");
	_client->println("</head>");
}

#endif

