#ifndef _WEBSOCKET_WIFI_DEVICE_DRIVER_CONSTS_h
#define _WEBSOCKET_WIFI_DEVICE_DRIVER_CONSTS_h

#include "Wifi_Device_Driver_Consts.h"

static unsigned int const WEBSOCKET_WIFI_DEVICE_DRIVER_TYPE = DEVICE_DRIVER_LAST_MESSAGE + 1010000;
static unsigned int const WEBSOCKET_WIFI_DEVICE_DRIVER_LAST_MESSAGE = WEBSOCKET_WIFI_DEVICE_DRIVER_TYPE;

static void SendHeader(WiFiClient *_client) {

	_client->println(F("<head>"));
	_client->println(F("    <title>Bilderrahme</title>"));
	_client->println(F("    <meta charset=\"utf-8\">"));
	_client->println(F("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"));
	_client->println(F("    <!--  CSS -->"));
	_client->println(F("    <link rel=\"stylesheet\" href=\"dist/css/kube.min.css\">"));
	_client->println(F("    <!-- SCRIPT -->"));
	_client->println(F("    <script type=\"text/javascript\" src=\"dist/js/jscolor.min.js\"></script>"));
	_client->println(F("    <script>"));
	_client->println(F("        function openTab(evt, tabName) {"));
	_client->println(F("            var i, tabcontent, tablinks;"));
	_client->println(F("            tabcontent = document.getElementsByClassName(\"tabcontent\");"));
	_client->println(F("            for (i = 0; i < tabcontent.length; i++) {"));
	_client->println(F("                tabcontent[i].style.display = \"none\";"));
	_client->println(F("            }"));
	_client->println(F("            tablinks = document.getElementsByClassName(\"tablinks\");"));
	_client->println(F("            for (i = 0; i < tablinks.length; i++) {"));
	_client->println(F("                tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");"));
	_client->println(F("            }"));
	_client->println(F("            document.getElementById(tabName).style.display = \"block\";"));
	_client->println(F("            evt.currentTarget.className += \" active\";"));
	_client->println(F("        }"));
	_client->println(F("        var connection = new WebSocket(\"ws://\" + location.hostname + \":81/\", [\"arduino\"]);"));
	_client->println(F("        connection.onopen = function () { connection.send(\"Connect \" + new Date()); };"));
	_client->println(F("        connection.onerror = function (error) { console.log(\"WebSocket Error \", error); };"));
	_client->println(F("        connection.onmessage = function (e) {"));
	_client->println(F("            if (e.data.indexOf(\"subProtocol\") == -1) {"));
	_client->println(F("                var jsonObject = eval(\"(\" + e.data + \")\");"));
	_client->println(F("                var deviceId = jsonObject._deviceId;"));
	_client->println(F("                var cmdId = jsonObject._cmdId;"));
	_client->println(F("                var value = jsonObject._value;"));
	_client->println(F("                var unit = jsonObject._unit;"));
	_client->println(F("                var search_id = deviceId.toString() + \"_\" + cmdId.toString();"));
	_client->println(F("                document.getElementById(search_id).value = value + \" \" + unit;"));
	_client->println(F("            };"));
	_client->println(F("        };"));
	_client->println(F("        function SendMessage(_deviceId, _cmdId, _value) {"));
	_client->println(F("            var search_id = _deviceId.toString() + \"_\" + _cmdId.toString();"));
	_client->println(F("            var obj = new Object();"));
	_client->println(F("            obj.deviceId = _deviceId;"));
	_client->println(F("            obj.cmdId = _cmdId;"));
	_client->println(F("            if (typeof _value !== \"undefined\") {"));
	_client->println(F("				obj.value = _value;"));
	_client->println(F("            }"));
	_client->println(F("            else {"));
	_client->println(F("				obj.value = document.getElementById(search_id).value;"));
	_client->println(F("            }"));
	_client->println(F("            var jsonString = JSON.stringify(obj);"));
	_client->println(F("            connection.send(jsonString);"));
	_client->println(F("        };"));
	_client->println(F("    </script>"));
	_client->println(F("    <style>"));
	_client->println(F("        body {"));
	_client->println(F("            font-family: helvetica, arial, sans-serif;"));
	_client->println(F("            margin-left: 5%;"));
	_client->println(F("            margin-right: 5%;"));
	_client->println(F("            background-color: #DFFFDF;"));
	_client->println(F("            min-width: 250px;"));
	_client->println(F("        }"));
	_client->println(F("        .simple-text {"));
	_client->println(F("            color: #e3e3e3;"));
	_client->println(F("            text-shadow: 1px 1px 0px black;"));
	_client->println(F("        }"));
	_client->println(F("        div.tab {"));
	_client->println(F("            overflow: hidden;"));
	_client->println(F("            background: -moz-linear-gradient(top, #e3e3e3, #c8c8c8);"));
	_client->println(F("            background: -webkit-gradient(linear, left top, left bottom, from(#e3e3e3), to(#c8c8c8));"));
	_client->println(F("        }"));
	_client->println(F("            div.tab button {"));
	_client->println(F("                background-color: inherit;"));
	_client->println(F("                float: left;"));
	_client->println(F("                border: none;"));
	_client->println(F("                outline: none;"));
	_client->println(F("                padding: 14px 16px;"));
	_client->println(F("                transition: 0.3s;"));
	_client->println(F("                font-size: 17px;"));
	_client->println(F("                color: #454545;"));
	_client->println(F("            }"));
	_client->println(F("                div.tab button:hover {"));
	_client->println(F("                    background-color: #ddd;"));
	_client->println(F("                }"));
	_client->println(F("                div.tab button.active {"));
	_client->println(F("                    background-color: #ccc;"));
	_client->println(F("                }"));
	_client->println(F("        .tabcontent {"));
	_client->println(F("            display: none;"));
	_client->println(F("            padding: 12px 15px;"));
	_client->println(F("        }"));
	_client->println(F("        .container {"));
	_client->println(F("            background: #666;"));
	_client->println(F("            padding-top: 30px;"));
	_client->println(F("        }"));
	_client->println(F("        .head-line {"));
	_client->println(F("            background: #e3e3e3;"));
	_client->println(F("            position: relative;"));
	_client->println(F("            background: -moz-linear-gradient(top, #e3e3e3, #c8c8c8);"));
	_client->println(F("            background: -webkit-gradient(linear, left top, left bottom, from(#e3e3e3), to(#c8c8c8));"));
	_client->println(F("            padding: 10px 20px;"));
	_client->println(F("            margin-left: -10px;"));
	_client->println(F("            width: 70%;"));
	_client->println(F("            max-width: 550px;"));
	_client->println(F("            min-width: 300px;"));
	_client->println(F("            -moz-box-shadow: 1px 1px 3px #292929;"));
	_client->println(F("            -webkit-box-shadow: 1px 1px 3px #292929;"));
	_client->println(F("            color: #454545;"));
	_client->println(F("            text-shadow: 0 1px 0 white;"));
	_client->println(F("        }"));
	_client->println(F("            .head-line.small {"));
	_client->println(F("                width: 30%;"));
	_client->println(F("                margin-left: -20px;"));
	_client->println(F("                min-width: 200px;"));
	_client->println(F("                max-width: 250px;"));
	_client->println(F("                font-size: 1.3em;"));
	_client->println(F("                line-height: 0.8em;"));
	_client->println(F("                font-family: Tahoma, Verdana, Segoe, sans-serif;"));
	_client->println(F("            }"));
	_client->println(F("        .button {"));
	_client->println(F("            font-size: 18px;"));
	_client->println(F("            font-weight: bold;"));
	_client->println(F("            background: #e3e3e3;"));
	_client->println(F("            position: relative;"));
	_client->println(F("            background: -moz-linear-gradient(top, #e3e3e3, #c8c8c8);"));
	_client->println(F("            background: -webkit-gradient(linear, left top, left bottom, from(#e3e3e3), to(#c8c8c8));"));
	_client->println(F("            -moz-box-shadow: 1px 1px 3px #292929;"));
	_client->println(F("            -webkit-box-shadow: 1px 1px 3px #292929;"));
	_client->println(F("            color: #454545;"));
	_client->println(F("            text-shadow: 0 1px 0 white;"));
	_client->println(F("            margin-right: 15px;"));
	_client->println(F("        }"));
	_client->println(F("            .button:hover {"));
	_client->println(F("                background-color: #454545;"));
	_client->println(F("                color: #454545;"));
	_client->println(F("            }"));
	_client->println(F("            .button:active {"));
	_client->println(F("                box-shadow: 0 2px 0 #393939, 0 4px 4px rgba(0, 0, 0, 0.4), 0 2px 5px rgba(0, 0, 0, 0.2) inset;"));
	_client->println(F("                top: 2px;"));
	_client->println(F("            }"));
	_client->println(F("        .desc {"));
	_client->println(F("            color: #454545;"));
	_client->println(F("        }"));
	_client->println(F("    </style>"));
	_client->println(F("</head>"));
}

#endif


