#ifndef _WEBSOCKET_WIFI_DEVICE_DRIVER_CONSTS_h
#define _WEBSOCKET_WIFI_DEVICE_DRIVER_CONSTS_h

#include "Wifi_Device_Driver_Consts.h"

static unsigned int const WEBSOCKET_WIFI_DEVICE_DRIVER_TYPE = WIFI_DEVICE_DRIVER_TYPE + 200;
static unsigned int const WEBSOCKET_WIFI_DEVICE_DRIVER_LAST_MESSAGE = WEBSOCKET_WIFI_DEVICE_DRIVER_TYPE;

static void SendHeader(WiFiClient *_client) {

	_client->println("<head>");
	_client->println("    <title>Bilderrahme</title>");
	_client->println("    <meta charset=\"utf-8\">");
	_client->println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
	_client->println("    <!--  CSS -->");
	_client->println("    <link rel=\"stylesheet\" href=\"dist/css/kube.min.css\">");
	_client->println("    <!-- SCRIPT -->");
	_client->println("    <script type=\"text/javascript\" src=\"dist/js/jscolor.min.js\"></script>");
	_client->println("    <script>");
	_client->println("        function openTab(evt, tabName) {");
	_client->println("            var i, tabcontent, tablinks;");
	_client->println("            tabcontent = document.getElementsByClassName(\"tabcontent\");");
	_client->println("            for (i = 0; i < tabcontent.length; i++) {");
	_client->println("                tabcontent[i].style.display = \"none\";");
	_client->println("            }");
	_client->println("            tablinks = document.getElementsByClassName(\"tablinks\");");
	_client->println("            for (i = 0; i < tablinks.length; i++) {");
	_client->println("                tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");");
	_client->println("            }");
	_client->println("            document.getElementById(tabName).style.display = \"block\";");
	_client->println("            evt.currentTarget.className += \" active\";");
	_client->println("        }");
	_client->println("        var connection = new WebSocket(\"ws://\" + location.hostname + \":81/\", [\"arduino\"]);");
	_client->println("        connection.onopen = function () { connection.send(\"Connect \" + new Date()); };");
	_client->println("        connection.onerror = function (error) { console.log(\"WebSocket Error \", error); };");
	_client->println("        connection.onmessage = function (e) {");
	_client->println("            if (e.data.indexOf(\"subProtocol\") == -1) {");
	_client->println("                var jsonObject = eval(\"(\" + e.data + \")\");");
	_client->println("                var deviceId = jsonObject._deviceId;");
	_client->println("                var cmdId = jsonObject._cmdId;");
	_client->println("                var value = jsonObject._value;");
	_client->println("                var unit = jsonObject._unit;");
	_client->println("                var search_id = deviceId.toString() + \"_\" + cmdId.toString();");
	_client->println("                document.getElementById(search_id).placeholder = value + \" \" + unit;");
	_client->println("            };");
	_client->println("        };");
	_client->println("        function SendMessage(_deviceId, _cmdId, _value) {");
	_client->println("            var search_id = _deviceId.toString() + \"_\" + _cmdId.toString();");
	_client->println("            var obj = new Object();");
	_client->println("            obj.deviceId = _deviceId;");
	_client->println("            obj.cmdId = _cmdId;");
	_client->println("            if (typeof _value !== \"undefined\") {");
	_client->println("				obj.value = _value;");
	_client->println("            }");
	_client->println("            else {");
	_client->println("				obj.value = document.getElementById(search_id).value;");
	_client->println("            }");
	_client->println("            var jsonString = JSON.stringify(obj);");
	_client->println("            connection.send(jsonString);");
	_client->println("        };");
	_client->println("    </script>");
	_client->println("    <style>");
	_client->println("        body {");
	_client->println("            font-family: helvetica, arial, sans-serif;");
	_client->println("            margin-left: 5%;");
	_client->println("            margin-right: 5%;");
	_client->println("            background-color: #DFFFDF;");
	_client->println("            min-width: 250px;");
	_client->println("        }");
	_client->println("        .simple-text {");
	_client->println("            color: #e3e3e3;");
	_client->println("            text-shadow: 1px 1px 0px black;");
	_client->println("        }");
	_client->println("        div.tab {");
	_client->println("            overflow: hidden;");
	_client->println("            background: -moz-linear-gradient(top, #e3e3e3, #c8c8c8);");
	_client->println("            background: -webkit-gradient(linear, left top, left bottom, from(#e3e3e3), to(#c8c8c8));");
	_client->println("        }");
	_client->println("            div.tab button {");
	_client->println("                background-color: inherit;");
	_client->println("                float: left;");
	_client->println("                border: none;");
	_client->println("                outline: none;");
	_client->println("                padding: 14px 16px;");
	_client->println("                transition: 0.3s;");
	_client->println("                font-size: 17px;");
	_client->println("                color: #454545;");
	_client->println("            }");
	_client->println("                div.tab button:hover {");
	_client->println("                    background-color: #ddd;");
	_client->println("                }");
	_client->println("                div.tab button.active {");
	_client->println("                    background-color: #ccc;");
	_client->println("                }");
	_client->println("        .tabcontent {");
	_client->println("            display: none;");
	_client->println("            padding: 12px 15px;");
	_client->println("        }");
	_client->println("        .container {");
	_client->println("            background: #666;");
	_client->println("            padding-top: 30px;");
	_client->println("        }");
	_client->println("        .head-line {");
	_client->println("            background: #e3e3e3;");
	_client->println("            position: relative;");
	_client->println("            background: -moz-linear-gradient(top, #e3e3e3, #c8c8c8);");
	_client->println("            background: -webkit-gradient(linear, left top, left bottom, from(#e3e3e3), to(#c8c8c8));");
	_client->println("            padding: 10px 20px;");
	_client->println("            margin-left: -10px;");
	_client->println("            width: 70%;");
	_client->println("            max-width: 550px;");
	_client->println("            min-width: 300px;");
	_client->println("            -moz-box-shadow: 1px 1px 3px #292929;");
	_client->println("            -webkit-box-shadow: 1px 1px 3px #292929;");
	_client->println("            color: #454545;");
	_client->println("            text-shadow: 0 1px 0 white;");
	_client->println("        }");
	_client->println("            .head-line.small {");
	_client->println("                width: 30%;");
	_client->println("                margin-left: -20px;");
	_client->println("                min-width: 200px;");
	_client->println("                max-width: 250px;");
	_client->println("                font-size: 1.3em;");
	_client->println("                line-height: 0.8em;");
	_client->println("                font-family: Tahoma, Verdana, Segoe, sans-serif;");
	_client->println("            }");
	_client->println("        .button {");
	_client->println("            font-size: 18px;");
	_client->println("            font-weight: bold;");
	_client->println("            background: #e3e3e3;");
	_client->println("            position: relative;");
	_client->println("            background: -moz-linear-gradient(top, #e3e3e3, #c8c8c8);");
	_client->println("            background: -webkit-gradient(linear, left top, left bottom, from(#e3e3e3), to(#c8c8c8));");
	_client->println("            -moz-box-shadow: 1px 1px 3px #292929;");
	_client->println("            -webkit-box-shadow: 1px 1px 3px #292929;");
	_client->println("            color: #454545;");
	_client->println("            text-shadow: 0 1px 0 white;");
	_client->println("            margin-right: 15px;");
	_client->println("        }");
	_client->println("            .button:hover {");
	_client->println("                background-color: #454545;");
	_client->println("                color: #454545;");
	_client->println("            }");
	_client->println("            .button:active {");
	_client->println("                box-shadow: 0 2px 0 #393939, 0 4px 4px rgba(0, 0, 0, 0.4), 0 2px 5px rgba(0, 0, 0, 0.2) inset;");
	_client->println("                top: 2px;");
	_client->println("            }");
	_client->println("        .desc {");
	_client->println("            color: #454545;");
	_client->println("        }");
	_client->println("    </style>");
	_client->println("</head>");
}

#endif


